-- Ark Kids three-year scope & sequence year plans.
-- Source: ark-kids-scope-and-sequence.pdf + api.lessons.church/lessons/public/tree
-- DO NOT run against production without an explicit ops review.
-- churchId BVLAFRqSzX0 is the Ark Kids publisher (programs.churchId).
-- Year 3 omits Connect and Creation (Coming Soon on the PDF; not in the catalog).
-- In Step is one 9-lesson study; PDF lists Part 1 (4) + Part 2 (4). Seed uses weeks 1-4 then 5-9.
-- Summer to the Max Vol. 1 has 8 catalog lessons (PDF says 9). Guard Your Heart has 3 (PDF says 4).
-- Specials are stand-alones from the PDF footer, not inserted into the 48-week years.

START TRANSACTION;
DELETE FROM yearPlanWeeks WHERE yearPlanId IN ('YPLArkElY01', 'YPLArkElY02', 'YPLArkElY03', 'YPLArkElSpc', 'YPLArkJrY01', 'YPLArkJrY02', 'YPLArkJrY03', 'YPLArkJrSpc');
DELETE FROM yearPlans WHERE id IN ('YPLArkElY01', 'YPLArkElY02', 'YPLArkElY03', 'YPLArkElSpc', 'YPLArkJrY01', 'YPLArkJrY02', 'YPLArkJrY03', 'YPLArkJrSpc');

INSERT INTO yearPlans (id, churchId, name, slug, programId, venuePreference, sort, live) VALUES
('YPLArkElY01', 'BVLAFRqSzX0', 'Ark Kids Elementary Year 1', 'ark-elementary-year-1', 'BVLAFRqSzX0', 'Large Group Full Program, Large Group Full, Large Group', 1, 1),
('YPLArkElY02', 'BVLAFRqSzX0', 'Ark Kids Elementary Year 2', 'ark-elementary-year-2', 'BVLAFRqSzX0', 'Large Group Full Program, Large Group Full, Large Group', 2, 1),
('YPLArkElY03', 'BVLAFRqSzX0', 'Ark Kids Elementary Year 3', 'ark-elementary-year-3', 'BVLAFRqSzX0', 'Large Group Full Program, Large Group Full, Large Group', 3, 1),
('YPLArkElSpc', 'BVLAFRqSzX0', 'Ark Kids Elementary Specials', 'ark-elementary-specials', 'BVLAFRqSzX0', 'Large Group Full Program, Large Group Full, Large Group', 4, 1),
('YPLArkJrY01', 'BVLAFRqSzX0', 'Ark Kids Junior Year 1', 'ark-junior-year-1', 'BVLAFRqSzX1', 'Large Group, Classroom', 5, 1),
('YPLArkJrY02', 'BVLAFRqSzX0', 'Ark Kids Junior Year 2', 'ark-junior-year-2', 'BVLAFRqSzX1', 'Large Group, Classroom', 6, 1),
('YPLArkJrY03', 'BVLAFRqSzX0', 'Ark Kids Junior Year 3', 'ark-junior-year-3', 'BVLAFRqSzX1', 'Large Group, Classroom', 7, 1),
('YPLArkJrSpc', 'BVLAFRqSzX0', 'Ark Kids Junior Specials', 'ark-junior-specials', 'BVLAFRqSzX1', 'Large Group, Classroom', 8, 1);

INSERT INTO yearPlanWeeks (id, churchId, yearPlanId, week, lessonId, programId, studyId, venueId, studyName, lessonName, venueName) VALUES
('YPWE1000001', 'BVLAFRqSzX0', 'YPLArkElY01', 1, 'j82PgGV93h6', 'BVLAFRqSzX0', 'dXL2VJFn9u6', 'Lt7pLedDHEg', 'The Helper', 'The Helper Week 1: The Holy Spirit Is Our Helper', 'Large Group Full Program'),
('YPWE1000002', 'BVLAFRqSzX0', 'YPLArkElY01', 2, 'm6CSt67sCMb', 'BVLAFRqSzX0', 'dXL2VJFn9u6', '7QN8GvADktV', 'The Helper', 'The Helper Week 2: The Holy Spirit Is Our Guide', 'Large Group Full Program'),
('YPWE1000003', 'BVLAFRqSzX0', 'YPLArkElY01', 3, 'JWfPzIx5sCl', 'BVLAFRqSzX0', 'dXL2VJFn9u6', '4LNG-m0TgJb', 'The Helper', 'The Helper Week 3: The Holy Spirit Is Our Comforter', 'Large Group Full Program'),
('YPWE1000004', 'BVLAFRqSzX0', 'YPLArkElY01', 4, 'PuyBi0ztbvy', 'BVLAFRqSzX0', 'dXL2VJFn9u6', '55fYQff52XW', 'The Helper', 'The Helper Week 4: The Holy Spirit Is Our Source', 'Large Group Full Program'),
('YPWE1000005', 'BVLAFRqSzX0', 'YPLArkElY01', 5, 'WrSaAldw6IR', 'BVLAFRqSzX0', 'Q-0BwYmaBJj', '3tWIbO3K8ZO', 'Love God, Love Others', 'Love God, Love Others Week 1: Love God The Most', 'Large Group Full Program'),
('YPWE1000006', 'BVLAFRqSzX0', 'YPLArkElY01', 6, 'SE0lK_9fgj7', 'BVLAFRqSzX0', 'Q-0BwYmaBJj', 'HmJxaRxWzbj', 'Love God, Love Others', 'Love God, Love Others Week 2: Love God With Everything', 'Large Group Full Program'),
('YPWE1000007', 'BVLAFRqSzX0', 'YPLArkElY01', 7, 'O6jNn1y7bXb', 'BVLAFRqSzX0', 'Q-0BwYmaBJj', '2InLsZfwG90', 'Love God, Love Others', 'Love God, Love Others Week 3:  Love Your Neighbor', 'Large Group Full Program'),
('YPWE1000008', 'BVLAFRqSzX0', 'YPLArkElY01', 8, 'm0lrjaAdG44', 'BVLAFRqSzX0', 'Q-0BwYmaBJj', '99A97kZN7G8', 'Love God, Love Others', 'Love God, Love Others Week 4: Love Your Neighbor As Yourself', 'Large Group Full Program'),
('YPWE1000009', 'BVLAFRqSzX0', 'YPLArkElY01', 9, '3gHzotXMwU_', 'BVLAFRqSzX0', 'ywlQ01bY8-Q', 'Dng7VUR02tz', 'Jesus Is', 'Jesus Is Week 1: Jesus Is The Bread Of Life', 'Large Group Full Program'),
('YPWE1000010', 'BVLAFRqSzX0', 'YPLArkElY01', 10, 'Z0L_QrZVwx2', 'BVLAFRqSzX0', 'ywlQ01bY8-Q', 'a4D6y_eVCR0', 'Jesus Is', 'Jesus Is Week 2: Jesus Is The Good Shepherd', 'Large Group Full Program'),
('YPWE1000011', 'BVLAFRqSzX0', 'YPLArkElY01', 11, 'GJB1TFlEKDw', 'BVLAFRqSzX0', 'ywlQ01bY8-Q', 'i0fan0L9ROU', 'Jesus Is', 'Jesus Is Week 3: Jesus Is The Light Of The World', 'Large Group Full Program'),
('YPWE1000012', 'BVLAFRqSzX0', 'YPLArkElY01', 12, 'NiZ_dOFsQVC', 'BVLAFRqSzX0', 'ywlQ01bY8-Q', 'BNNwoorQJJ2', 'Jesus Is', 'Jesus Is Week 4: Jesus Is The Resurrection And The Life', 'Large Group Full Program'),
('YPWE1000013', 'BVLAFRqSzX0', 'YPLArkElY01', 13, 'kPyqWVz2Ft1', 'BVLAFRqSzX0', '0m2GhKa4AbV', 'AUxR0WumigI', 'Let''s Chat', 'Let''s Chat Week 1: I Can Pray', 'Large Group Full Program'),
('YPWE1000014', 'BVLAFRqSzX0', 'YPLArkElY01', 14, 'CCrh3KjAUsX', 'BVLAFRqSzX0', '0m2GhKa4AbV', 'o2zzDNbludN', 'Let''s Chat', 'Let''s Chat Week 2:  I Can Pray Anytime', 'Large Group Full Program'),
('YPWE1000015', 'BVLAFRqSzX0', 'YPLArkElY01', 15, 'A04XZS8lSLq', 'BVLAFRqSzX0', '0m2GhKa4AbV', 'g0AuUWkq6Nm', 'Let''s Chat', 'Let''s Chat Week 3: I Can Pray From My Heart', 'Large Group Full Program'),
('YPWE1000016', 'BVLAFRqSzX0', 'YPLArkElY01', 16, 'ahMZLIPcLtg', 'BVLAFRqSzX0', '0m2GhKa4AbV', '0Ct7Iq01vDb', 'Let''s Chat', 'Let''s Chat Week 4: God Listens When I Pray', 'Large Group Full Program'),
('YPWE1000017', 'BVLAFRqSzX0', 'YPLArkElY01', 17, 'LokAPfneEmp', 'BVLAFRqSzX0', '0Rwa3q9FjpE', 'a9sN2tBwpkM', 'Go (Missions Series)', 'Go Week 1: I Can Go!', 'Large Group'),
('YPWE1000018', 'BVLAFRqSzX0', 'YPLArkElY01', 18, 'eIrCiSASf1L', 'BVLAFRqSzX0', '0Rwa3q9FjpE', 'PHkSGD5RZZA', 'Go (Missions Series)', 'Go Week 2: I Can Tell!', 'Large Group'),
('YPWE1000019', 'BVLAFRqSzX0', 'YPLArkElY01', 19, 'AAH0HLQTQzu', 'BVLAFRqSzX0', '0Rwa3q9FjpE', '50B1hrT1VLh', 'Go (Missions Series)', 'Go Week 3: I Can Give!', 'Large Group'),
('YPWE1000020', 'BVLAFRqSzX0', 'YPLArkElY01', 20, '05o8SOxJYaD', 'BVLAFRqSzX0', '0Rwa3q9FjpE', '9eY0XXWsjcC', 'Go (Missions Series)', 'Go Week 4: I Can Keep Going!', 'Large Group'),
('YPWE1000021', 'BVLAFRqSzX0', 'YPLArkElY01', 21, 't88mCvZMnyO', 'BVLAFRqSzX0', 'htBJRBM7kqs', 'LaaRFKqNV87', 'Summer to the Max', 'Summer to the Max Week 1: I Can Honor God', 'Large Group Full Program'),
('YPWE1000022', 'BVLAFRqSzX0', 'YPLArkElY01', 22, 'jv4z0auJbJR', 'BVLAFRqSzX0', 'htBJRBM7kqs', 'l7VVrNFq9ka', 'Summer to the Max', 'Summer to the Max Week 2: I Can Obey God', 'Large Group Full Program'),
('YPWE1000023', 'BVLAFRqSzX0', 'YPLArkElY01', 23, 'GqDDDbpzMTF', 'BVLAFRqSzX0', 'htBJRBM7kqs', 'rO2rE-uU1LT', 'Summer to the Max', 'Summer to the Max Week 3: I Can Believe God’s Word', 'Large Group Full Program'),
('YPWE1000024', 'BVLAFRqSzX0', 'YPLArkElY01', 24, '0Hw1qG4X02b', 'BVLAFRqSzX0', 'htBJRBM7kqs', 'SbJ0SaSytk5', 'Summer to the Max', 'Summer to the Max Week 4: I Can Do The Right Thing', 'Large Group Full Program'),
('YPWE1000025', 'BVLAFRqSzX0', 'YPLArkElY01', 25, 'PElqRmk7ElJ', 'BVLAFRqSzX0', 'htBJRBM7kqs', '9HcThV2FL-a', 'Summer to the Max', 'Summer to the Max Week 5: I Can Serve', 'Large Group Full Program'),
('YPWE1000026', 'BVLAFRqSzX0', 'YPLArkElY01', 26, 'fZbehgyVVYg', 'BVLAFRqSzX0', 'htBJRBM7kqs', 'wxoSNpXKm19', 'Summer to the Max', 'Summer to the Max Week 6: I Can Change', 'Large Group Full Program'),
('YPWE1000027', 'BVLAFRqSzX0', 'YPLArkElY01', 27, '1cQszGcarnZ', 'BVLAFRqSzX0', 'htBJRBM7kqs', '1MH6dJ0kDUc', 'Summer to the Max', 'Summer to the Max Week 7: I Can Speak the Truth', 'Large Group Full Program'),
('YPWE1000028', 'BVLAFRqSzX0', 'YPLArkElY01', 28, 'Bl8eKsfeLiY', 'BVLAFRqSzX0', 'htBJRBM7kqs', '0rMnn0TRmXj', 'Summer to the Max', 'Summer to the Max Week 8: I Can Step Up', 'Large Group Full Program'),
('YPWE1000029', 'BVLAFRqSzX0', 'YPLArkElY01', 29, 'zBnXdC2coRz', 'BVLAFRqSzX0', 'lGHAREpmqf-', 'i9gLJm2BOmk', 'In Step', 'In Step Week 1: Put Others First', 'Large Group Full Program'),
('YPWE1000030', 'BVLAFRqSzX0', 'YPLArkElY01', 30, 'tpj0yMdGzhs', 'BVLAFRqSzX0', 'lGHAREpmqf-', 'EvdI3E7smqN', 'In Step', 'In Step Week 2: Be Happy No Matter What', 'Large Group Full Program'),
('YPWE1000031', 'BVLAFRqSzX0', 'YPLArkElY01', 31, 'DAgdxKTIU75', 'BVLAFRqSzX0', 'lGHAREpmqf-', 'RVw38rvsmcG', 'In Step', 'In Step Week 3: Have a Peaceful Heart And Mind', 'Large Group Full Program'),
('YPWE1000032', 'BVLAFRqSzX0', 'YPLArkElY01', 32, 'mOl_q-SzHbI', 'BVLAFRqSzX0', 'lGHAREpmqf-', 'WXMMV4ZZ9Oe', 'In Step', 'In Step Week 4: Be Willing To Wait', 'Large Group Full Program'),
('YPWE1000033', 'BVLAFRqSzX0', 'YPLArkElY01', 33, 'FncThAxuSZk', 'BVLAFRqSzX0', 'lGHAREpmqf-', '7oUsNRIwibg', 'In Step', 'In Step Week 5: Care For Others', 'Large Group Full Program'),
('YPWE1000034', 'BVLAFRqSzX0', 'YPLArkElY01', 34, 'f1iZSrHnUUD', 'BVLAFRqSzX0', 'lGHAREpmqf-', 'EYuu2M1_zO0', 'In Step', 'In Step Week 6: Give Without Getting Back', 'Large Group Full Program'),
('YPWE1000035', 'BVLAFRqSzX0', 'YPLArkElY01', 35, 'aklao1spE0f', 'BVLAFRqSzX0', 'lGHAREpmqf-', 'SWjbyvGgPzx', 'In Step', 'In Step Week 7: Count On Me', 'Large Group Full Program'),
('YPWE1000036', 'BVLAFRqSzX0', 'YPLArkElY01', 36, '1KUvEETuZSv', 'BVLAFRqSzX0', 'lGHAREpmqf-', 'nYn63ivlRjd', 'In Step', 'In Step Week 8: Use Your Power to Help', 'Large Group Full Program'),
('YPWE1000037', 'BVLAFRqSzX0', 'YPLArkElY01', 37, 'qbqGqRRMDNQ', 'BVLAFRqSzX0', 'lGHAREpmqf-', 'g90V600vrgY', 'In Step', 'In Step Week 9: Stay In Charge', 'Large Group Full Program'),
('YPWE1000038', 'BVLAFRqSzX0', 'YPLArkElY01', 38, 'Ygbj07HFu4-', 'BVLAFRqSzX0', 'YWIjJ7khVO6', '8C6GcIEPygp', 'The Bible Tells Me So', 'The Bible Tells Me So Week 1: The Bible Tells Me Who God Is', 'Large Group Full Program'),
('YPWE1000039', 'BVLAFRqSzX0', 'YPLArkElY01', 39, '8eIS-fRWgen', 'BVLAFRqSzX0', 'YWIjJ7khVO6', 'bHzSlr10Be0', 'The Bible Tells Me So', 'The Bible Tells Me So Week 2: The Bible Tells Me Who I Am', 'Large Group Full Program'),
('YPWE1000040', 'BVLAFRqSzX0', 'YPLArkElY01', 40, 'pAkOxerd7TA', 'BVLAFRqSzX0', 'YWIjJ7khVO6', 'KpApyGg7oa-', 'The Bible Tells Me So', 'The Bible Tells Me So Week 3: The Bible Tells Me What God Can Do', 'Large Group Full Program'),
('YPWE1000041', 'BVLAFRqSzX0', 'YPLArkElY01', 41, '4LpxjHFsjgy', 'BVLAFRqSzX0', 'YWIjJ7khVO6', 'oIwpvfMnH4e', 'The Bible Tells Me So', 'The Bible Tells Me So Week 4: The Bible Tells Me What I Can Do', 'Large Group Full Program'),
('YPWE1000042', 'BVLAFRqSzX0', 'YPLArkElY01', 42, 'ZJ4oZuH9zZ9', 'BVLAFRqSzX0', 'dRek7wKbkCz', 'yAmPR9JfHFI', 'I’m Part of God''s Big Plan', 'I''m Part Of God''s Big Plan Week 1: Believe What God Says!', 'Large Group Full Program'),
('YPWE1000043', 'BVLAFRqSzX0', 'YPLArkElY01', 43, '5eAyVQy0MZA', 'BVLAFRqSzX0', 'dRek7wKbkCz', 'N6XozmsLV8B', 'I’m Part of God''s Big Plan', 'I''m Part Of God''s Big Plan Week 2: Don''t Give Up!', 'Large Group Full Program'),
('YPWE1000044', 'BVLAFRqSzX0', 'YPLArkElY01', 44, 'ZOWRFsbugq4', 'BVLAFRqSzX0', 'dRek7wKbkCz', 'b-4vS0--i09', 'I’m Part of God''s Big Plan', 'I''m Part Of God''s Big Plan Week 3: Use Your Gifts!', 'Large Group Full Program'),
('YPWE1000045', 'BVLAFRqSzX0', 'YPLArkElY01', 45, 'xo6lAkBSdbj', 'BVLAFRqSzX0', 'dRek7wKbkCz', '9uShOVp7Pk0', 'I’m Part of God''s Big Plan', 'I''m Part Of God''s Big Plan Week 4: Forgive And Let Go!', 'Large Group Full Program'),
('YPWE1000046', 'BVLAFRqSzX0', 'YPLArkElY01', 46, 'W1eeHaiVYic', 'BVLAFRqSzX0', '00h_6yow8jm', '4GYZRCF1-aX', 'The Good News of Christmas', 'The Good News of Christmas Week 1: God Can Use Me!', 'Large Group Full Program'),
('YPWE1000047', 'BVLAFRqSzX0', 'YPLArkElY01', 47, 'uq1-t6dHDG7', 'BVLAFRqSzX0', '00h_6yow8jm', 'q88ItmBdDEF', 'The Good News of Christmas', 'The Good News of Christmas Week 2: God Wants Me In His Family!', 'Large Group Full Program'),
('YPWE1000048', 'BVLAFRqSzX0', 'YPLArkElY01', 48, 'F6xA3dhOJD6', 'BVLAFRqSzX0', '00h_6yow8jm', 'FyUKvuAFFZz', 'The Good News of Christmas', 'The Good News of Christmas Week 3: Jesus Brings Joy At Christmas!', 'Large Group Full Program'),
('YPWE2000001', 'BVLAFRqSzX0', 'YPLArkElY02', 1, '_5fxHw0zW_r', 'BVLAFRqSzX0', 'uKWQf9LV0SQ', 'FeLAraK3YFc', 'Psalm 23', 'Psalm 23 Week 1: The Lord Is My Shepherd', 'Large Group Full Program'),
('YPWE2000002', 'BVLAFRqSzX0', 'YPLArkElY02', 2, '1jBOIWWs27P', 'BVLAFRqSzX0', 'uKWQf9LV0SQ', 'XkQqANogedI', 'Psalm 23', 'Psalm 23 Week 2: The Lord Is My Protector', 'Large Group Full Program'),
('YPWE2000003', 'BVLAFRqSzX0', 'YPLArkElY02', 3, 'xjjL5gvdRFq', 'BVLAFRqSzX0', 'uKWQf9LV0SQ', 'lgO8ys9Om9U', 'Psalm 23', 'Psalm 23 Week 3: The Lord Is My Provider', 'Large Group Full Program'),
('YPWE2000004', 'BVLAFRqSzX0', 'YPLArkElY02', 4, 'm7hwClM1uVR', 'BVLAFRqSzX0', 'uKWQf9LV0SQ', 's6PutzkAmrU', 'Psalm 23', 'Psalm 23 Week 4: The Lord Is My Hope', 'Large Group Full Program'),
('YPWE2000005', 'BVLAFRqSzX0', 'YPLArkElY02', 5, 'o1mGmfriBlf', 'BVLAFRqSzX0', '4RcBSwdZNF1', 'rKKvXyLnWkv', 'Guard Your Heart', 'Guard Your Heart Week 1: Guard Your Heart', 'Large Group Full Program'),
('YPWE2000006', 'BVLAFRqSzX0', 'YPLArkElY02', 6, 'w5XpY5XaXdi', 'BVLAFRqSzX0', '4RcBSwdZNF1', '3U0A1F9wj8u', 'Guard Your Heart', 'Guard Your Heart Week 2: Keep Out The Bad', 'Large Group Full Program'),
('YPWE2000007', 'BVLAFRqSzX0', 'YPLArkElY02', 7, 'jfoXj5TH7Dn', 'BVLAFRqSzX0', '4RcBSwdZNF1', 'vB4Qlh8zoQF', 'Guard Your Heart', 'Guard Your Heart Week 3: Put In The Good', 'Large Group Full Program'),
('YPWE2000008', 'BVLAFRqSzX0', 'YPLArkElY02', 8, 'c_QyzpzsB6z', 'BVLAFRqSzX0', 'LxylFzfeFwd', 'ZLNa0S7zrC4', 'Winter to the Max', 'Winter to the Max Week 1: I Will Value Jesus!', 'Large Group Full Program'),
('YPWE2000009', 'BVLAFRqSzX0', 'YPLArkElY02', 9, 'Bgul91LzKZA', 'BVLAFRqSzX0', 'LxylFzfeFwd', 'F67BwDWX68Q', 'Winter to the Max', 'Winter to the Max Week 2: I Will Follow Jesus', 'Large Group Full Program'),
('YPWE2000010', 'BVLAFRqSzX0', 'YPLArkElY02', 10, '-aDYdOjOTWv', 'BVLAFRqSzX0', 'LxylFzfeFwd', 'cEl8wF8AMRk', 'Winter to the Max', 'Winter to the Max Week 3: I Will Listen To Jesus', 'Large Group Full Program'),
('YPWE2000011', 'BVLAFRqSzX0', 'YPLArkElY02', 11, 'beJCGrePOvk', 'BVLAFRqSzX0', 'LxylFzfeFwd', 'JRGHTBHh-Yo', 'Winter to the Max', 'Winter to the Max Week 4: I Will Obey Jesus', 'Large Group Full Program'),
('YPWE2000012', 'BVLAFRqSzX0', 'YPLArkElY02', 12, 't4s-pujmDEI', 'BVLAFRqSzX0', 'yjvM27FBJyb', 'KKHqVpjsXHV', 'Power Up (Easter Series)', 'Power Up Week 1: I Can Obey! Easter Lesson', 'Large Group Full Program'),
('YPWE2000013', 'BVLAFRqSzX0', 'YPLArkElY02', 13, 'Q6U79OEAV1r', 'BVLAFRqSzX0', 'yjvM27FBJyb', 'oBnH73PhXrt', 'Power Up (Easter Series)', 'Power Up Week 2: I Can Serve!', 'Large Group Full Program'),
('YPWE2000014', 'BVLAFRqSzX0', 'YPLArkElY02', 14, '5wdROOcZEdy', 'BVLAFRqSzX0', 'yjvM27FBJyb', 'lXRS8771trb', 'Power Up (Easter Series)', 'Power Up Week 3: I Can Be Humble!', 'Large Group Full Program'),
('YPWE2000015', 'BVLAFRqSzX0', 'YPLArkElY02', 15, 'VMpwk3JXSEV', 'BVLAFRqSzX0', 'yjvM27FBJyb', 'cJHD2BmjhDq', 'Power Up (Easter Series)', 'Power Up Week 4: I Can Make Wise Choices!', 'Large Group Full Program'),
('YPWE2000016', 'BVLAFRqSzX0', 'YPLArkElY02', 16, 'vvQ1umPynZ8', 'BVLAFRqSzX0', 'lxH2yFmFU_A', 'AIz47GBlLJ2', 'Touring the Psalms', 'Touring the Psalms Week 1: I Will Praise God', 'Large Group Full Program'),
('YPWE2000017', 'BVLAFRqSzX0', 'YPLArkElY02', 17, 'i5OVEf7aJRE', 'BVLAFRqSzX0', 'lxH2yFmFU_A', 'Tu9PYEGznp7', 'Touring the Psalms', 'Touring the Psalms Week 2: I Praise God Because He Keeps His Promises', 'Large Group Full Program'),
('YPWE2000018', 'BVLAFRqSzX0', 'YPLArkElY02', 18, '7sR2S9bR72W', 'BVLAFRqSzX0', 'lxH2yFmFU_A', 'OfNfJ9vVVxF', 'Touring the Psalms', 'Touring the Psalms Week 3: I Won’t Stop Praising God', 'Large Group Full Program'),
('YPWE2000019', 'BVLAFRqSzX0', 'YPLArkElY02', 19, 'RXSfhY70Dm6', 'BVLAFRqSzX0', 'lxH2yFmFU_A', 'Vn8Hq6_wWgW', 'Touring the Psalms', 'Touring the Psalms Week 4: I Will Remember To Praise God', 'Large Group Full Program'),
('YPWE2000020', 'BVLAFRqSzX0', 'YPLArkElY02', 20, '-k-oj1v-bf0', 'BVLAFRqSzX0', 'hMyUFRJmdUQ', 'vnVhuDIRMnl', 'Summer To The Max, Vol. 2', 'Summer To The Max: Kick-Off', 'Large Group Full Program'),
('YPWE2000021', 'BVLAFRqSzX0', 'YPLArkElY02', 21, 'Ow0Xgunm8wR', 'BVLAFRqSzX0', 'hMyUFRJmdUQ', 'Eltsh7VVE2c', 'Summer To The Max, Vol. 2', 'Summer To The Max Lesson 1: I Am Helped', 'Large Group Full Program'),
('YPWE2000022', 'BVLAFRqSzX0', 'YPLArkElY02', 22, '-koZqz4ppIB', 'BVLAFRqSzX0', 'hMyUFRJmdUQ', '9XOm21Q4Fmb', 'Summer To The Max, Vol. 2', 'Summer To The Max Lesson 2: I Am Comforted', 'Large Group Full Program'),
('YPWE2000023', 'BVLAFRqSzX0', 'YPLArkElY02', 23, 'UiF74MPvd-2', 'BVLAFRqSzX0', 'hMyUFRJmdUQ', 'MzQ40Aup8v1', 'Summer To The Max, Vol. 2', 'Summer To The Max Lesson 3: I Am Humble', 'Large Group Full Program'),
('YPWE2000024', 'BVLAFRqSzX0', 'YPLArkElY02', 24, 'R0GcAJ-3IYG', 'BVLAFRqSzX0', 'hMyUFRJmdUQ', 'VHHExqhp-d7', 'Summer To The Max, Vol. 2', 'Summer To The Max Lesson 4: I Am Full', 'Large Group Full Program'),
('YPWE2000025', 'BVLAFRqSzX0', 'YPLArkElY02', 25, 'kSXG04fc55l', 'BVLAFRqSzX0', 'hMyUFRJmdUQ', 'Bb-lT2vbQUh', 'Summer To The Max, Vol. 2', 'Summer To The Max Lesson 5: I Am Merciful', 'Large Group Full Program'),
('YPWE2000026', 'BVLAFRqSzX0', 'YPLArkElY02', 26, 'oo-cFar6bkU', 'BVLAFRqSzX0', 'hMyUFRJmdUQ', '4gvaLOfGh_f', 'Summer To The Max, Vol. 2', 'Summer To The Max Lesson 6: I Am Sincere', 'Large Group Full Program'),
('YPWE2000027', 'BVLAFRqSzX0', 'YPLArkElY02', 27, 'Pz2Uj5thLuE', 'BVLAFRqSzX0', 'hMyUFRJmdUQ', 'HcL29wAOx7V', 'Summer To The Max, Vol. 2', 'Summer To The Max Lesson 7: I Am A Peacemaker', 'Large Group Full Program'),
('YPWE2000028', 'BVLAFRqSzX0', 'YPLArkElY02', 28, '1U533Vq10pA', 'BVLAFRqSzX0', 'hMyUFRJmdUQ', 'vzpw6RS6KoI', 'Summer To The Max, Vol. 2', 'Summer To The Max Lesson 8: I Am Happy No Matter What', 'Large Group Full Program'),
('YPWE2000029', 'BVLAFRqSzX0', 'YPLArkElY02', 29, 'wxsJ-USGR3s', 'BVLAFRqSzX0', 'YniW9qkc0UB', 'uxjEM0urlQX', 'Peace', 'Peace Week 1: I Can Have Peace When I’m Angry', 'Large Group Full Program'),
('YPWE2000030', 'BVLAFRqSzX0', 'YPLArkElY02', 30, 'uPRAIZq2aMv', 'BVLAFRqSzX0', 'YniW9qkc0UB', 'adZ8UdNxFHM', 'Peace', 'Peace Week 2: I Can Have Peace When I’m Afraid', 'Large Group Full Program'),
('YPWE2000031', 'BVLAFRqSzX0', 'YPLArkElY02', 31, 'oVw29yR3g1V', 'BVLAFRqSzX0', 'YniW9qkc0UB', '0v6FaKp7DIn', 'Peace', 'Peace Week 3: I Can Have Peace When I’m Sad', 'Large Group Full Program'),
('YPWE2000032', 'BVLAFRqSzX0', 'YPLArkElY02', 32, '6CwJSlyGH6z', 'BVLAFRqSzX0', 'YniW9qkc0UB', 'tsfPpsGhtaa', 'Peace', 'Peace Week 4: I Can Have Peace When I’m Disliked', 'Large Group Full Program'),
('YPWE2000033', 'BVLAFRqSzX0', 'YPLArkElY02', 33, 'WAbeNNe8MR7', 'BVLAFRqSzX0', 'DXhIow-cYdC', '8FkGTcxQHgL', 'Upside Down', 'Upside Down Week 1:  I Will Go God’s Way!', 'Large Group Full Program'),
('YPWE2000034', 'BVLAFRqSzX0', 'YPLArkElY02', 34, 'Xgp0OiXsVm5', 'BVLAFRqSzX0', 'DXhIow-cYdC', 'eXluGm0jw0z', 'Upside Down', 'Upside Down Week 2: I Will Only Worship God', 'Large Group Full Program'),
('YPWE2000035', 'BVLAFRqSzX0', 'YPLArkElY02', 35, 'SfmJwXMrFu0', 'BVLAFRqSzX0', 'DXhIow-cYdC', '5YY2lvydUaS', 'Upside Down', 'Upside Down Week 3: I Won''t Celebrate Bad Things!', 'Large Group Full Program'),
('YPWE2000036', 'BVLAFRqSzX0', 'YPLArkElY02', 36, 'iQf5WGiTNYO', 'BVLAFRqSzX0', 'DXhIow-cYdC', 'kq3WmNau2Th', 'Upside Down', 'Upside Down Week 4:  I Won''t Back Down', 'Large Group Full Program'),
('YPWE2000037', 'BVLAFRqSzX0', 'YPLArkElY02', 37, 'z94F-LcGdik', 'BVLAFRqSzX0', 'b8u9q9i7xiJ', 'haY9XOcH0EP', 'Don’t Fear', 'Don''t Fear Week 1: Don''t Fear, Jesus Is Strong!', 'Large Group Full Program'),
('YPWE2000038', 'BVLAFRqSzX0', 'YPLArkElY02', 38, 'SqhZg1bD8fO', 'BVLAFRqSzX0', 'b8u9q9i7xiJ', 'IvtbZDLpQQu', 'Don’t Fear', 'Don''t Fear Week 2: Don''t Fear, Jesus Wins!', 'Large Group Full Program'),
('YPWE2000039', 'BVLAFRqSzX0', 'YPLArkElY02', 39, 'A5nZ8Mia696', 'BVLAFRqSzX0', 'b8u9q9i7xiJ', 'Vw2mWWF8hkp', 'Don’t Fear', 'Don''t Fear Week 3: Don''t Fear, Jesus Is Just!', 'Large Group Full Program'),
('YPWE2000040', 'BVLAFRqSzX0', 'YPLArkElY02', 40, 'C6JBkTahgzh', 'BVLAFRqSzX0', 'b8u9q9i7xiJ', 'gbut0IzPfWN', 'Don’t Fear', 'Don''t Fear Week 4: Don''t Fear, Jesus Lives Forever!', 'Large Group Full Program'),
('YPWE2000041', 'BVLAFRqSzX0', 'YPLArkElY02', 41, 'spH7GlKJzq8', 'BVLAFRqSzX0', 'bPFHo0XspZC', 'iSkYEp0hjBt', 'All Aboard', 'All Aboard Week 1: I Have Faith To Give!', 'Large Group Full Program'),
('YPWE2000042', 'BVLAFRqSzX0', 'YPLArkElY02', 42, '7OYbNCntg5p', 'BVLAFRqSzX0', 'bPFHo0XspZC', 'H9Rt55HWW66', 'All Aboard', 'All Aboard Week 2: I Have Faith To Give When Jesus Asks!', 'Large Group Full Program'),
('YPWE2000043', 'BVLAFRqSzX0', 'YPLArkElY02', 43, 'KqRax4bW0-m', 'BVLAFRqSzX0', 'bPFHo0XspZC', 'P3y6AZm4SJo', 'All Aboard', 'All Aboard Week 3: I Have Faith To Give Freely!', 'Large Group Full Program'),
('YPWE2000044', 'BVLAFRqSzX0', 'YPLArkElY02', 44, '20Yw8wA4bUo', 'BVLAFRqSzX0', 'bPFHo0XspZC', '5Q59iKZ1I1b', 'All Aboard', 'All Aboard Week 4: I Have Faith To Give What I Have!', 'Large Group Full Program'),
('YPWE2000045', 'BVLAFRqSzX0', 'YPLArkElY02', 45, 'oLZnwOCAQbI', 'BVLAFRqSzX0', 'BnStvJXNoAl', 'keUjAEtkeEd', 'Better to Give (Christmas)', 'Better to Give Week 1: It''s Better to Give', 'Large Group Full Program'),
('YPWE2000046', 'BVLAFRqSzX0', 'YPLArkElY02', 46, 'y4EHxhpH0bS', 'BVLAFRqSzX0', 'BnStvJXNoAl', 'olM5yQ0guwD', 'Better to Give (Christmas)', 'Better to Give Week 2: Make Room To Give', 'Large Group Full Program'),
('YPWE2000047', 'BVLAFRqSzX0', 'YPLArkElY02', 47, 'yPzbrM2vTLg', 'BVLAFRqSzX0', 'BnStvJXNoAl', 'gExHt6HduFM', 'Better to Give (Christmas)', 'Better to Give Week 3: I Will Give My Best', 'Large Group Full Program'),
('YPWE3000001', 'BVLAFRqSzX0', 'YPLArkElY03', 1, '9HHpykwt3B3', 'BVLAFRqSzX0', 'pRpLYK0nH0S', 'XiQqYwZWMnw', 'God''s Love Is', 'God''s Love Is Week 1: God Is Love!', 'Large Group Full Program'),
('YPWE3000002', 'BVLAFRqSzX0', 'YPLArkElY03', 2, 'rV09IECYXWx', 'BVLAFRqSzX0', 'pRpLYK0nH0S', 'ItjSc-zoDS5', 'God''s Love Is', 'God''s Love Is Week 2: God''s Love Is Free!', 'Large Group Full Program'),
('YPWE3000003', 'BVLAFRqSzX0', 'YPLArkElY03', 3, 'jB0E7o2HiiL', 'BVLAFRqSzX0', 'pRpLYK0nH0S', 'rSHH3-1ODuH', 'God''s Love Is', 'God''s Love Is Week 3: God Loves Us No Matter What!', 'Large Group Full Program'),
('YPWE3000004', 'BVLAFRqSzX0', 'YPLArkElY03', 4, 'M3x3_7UvlPY', 'BVLAFRqSzX0', 'uzyYgNdUyl_', 'ApwsknOVHEr', 'More Like Jesus', 'More Like Jesus Week 1: Jesus Is Holy', 'Large Group Full Program'),
('YPWE3000005', 'BVLAFRqSzX0', 'YPLArkElY03', 5, '-YOcO-0vgQO', 'BVLAFRqSzX0', 'uzyYgNdUyl_', '_zYxZ9zabn9', 'More Like Jesus', 'More Like Jesus Week 2: I Love What Jesus Loves', 'Large Group Full Program'),
('YPWE3000006', 'BVLAFRqSzX0', 'YPLArkElY03', 6, '0JLXotqRpBQ', 'BVLAFRqSzX0', 'uzyYgNdUyl_', 'nULogiuI9lV', 'More Like Jesus', 'More Like Jesus Week 3: Jesus Helps Me To Be Holy', 'Large Group Full Program'),
('YPWE3000007', 'BVLAFRqSzX0', 'YPLArkElY03', 7, 'QdrujbjOMQk', 'BVLAFRqSzX0', 'uzyYgNdUyl_', 'MUUkTcVquEy', 'More Like Jesus', 'More Like Jesus Week 4: I Want To Be More Like Jesus', 'Large Group Full Program'),
('YPWE3000008', 'BVLAFRqSzX0', 'YPLArkElY03', 8, 'eEZwl2ovSM5', 'BVLAFRqSzX0', 'lq-vicQ-O_Q', 'eNLTurn00Ag', 'Made For Greatness', 'Made For Greatness Week 1: I Was Made Special', 'Large Group Full Program'),
('YPWE3000009', 'BVLAFRqSzX0', 'YPLArkElY03', 9, 'MN-FET3K_oO', 'BVLAFRqSzX0', 'lq-vicQ-O_Q', 'TMD-fW0T6Th', 'Made For Greatness', 'Made For Greatness Week 2: I Was Made Different', 'Large Group Full Program'),
('YPWE3000010', 'BVLAFRqSzX0', 'YPLArkElY03', 10, 'ZD0zh7CF1jK', 'BVLAFRqSzX0', 'lq-vicQ-O_Q', 'u9lPMz_sQJO', 'Made For Greatness', 'Made For Greatness Week 3: I Was Made To Never Give Up', 'Large Group Full Program'),
('YPWE3000011', 'BVLAFRqSzX0', 'YPLArkElY03', 11, '1LOZ8U_ssid', 'BVLAFRqSzX0', 'lq-vicQ-O_Q', 'ERtMVyiDzbs', 'Made For Greatness', 'Made For Greatness Week 4: I Was Made To Serve', 'Large Group Full Program'),
('YPWE3000012', 'BVLAFRqSzX0', 'YPLArkElY03', 12, 'cvvnbUXbHiU', 'BVLAFRqSzX0', 'SvoKl_NUJFo', 'r2bogkRPX-D', 'Summer To The Max, Vol. 3', 'Summer To The Max Kickoff: I Can Grow', 'Large Group Full Program'),
('YPWE3000013', 'BVLAFRqSzX0', 'YPLArkElY03', 13, 'RYKa-H_Sdll', 'BVLAFRqSzX0', 'SvoKl_NUJFo', 'SY05L7Luth9', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 1: I Can Trust In Jesus', 'Large Group Full Program'),
('YPWE3000014', 'BVLAFRqSzX0', 'YPLArkElY03', 14, 'PQa-shRbmJG', 'BVLAFRqSzX0', 'SvoKl_NUJFo', '6q0TyaVLRyQ', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 2: I Can Be More Like Jesus', 'Large Group Full Program'),
('YPWE3000015', 'BVLAFRqSzX0', 'YPLArkElY03', 15, '0hQUy2KDBgW', 'BVLAFRqSzX0', 'SvoKl_NUJFo', '5HG9jAFVB6P', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 3: I Can Learn From Jesus', 'Large Group Full Program'),
('YPWE3000016', 'BVLAFRqSzX0', 'YPLArkElY03', 16, 'AqCfIfn740D', 'BVLAFRqSzX0', 'SvoKl_NUJFo', 'j95Ekrtk99W', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 4: I Can Choose My Actions', 'Large Group Full Program'),
('YPWE3000017', 'BVLAFRqSzX0', 'YPLArkElY03', 17, '7_04ea8E3L2', 'BVLAFRqSzX0', 'SvoKl_NUJFo', '8XXr-MEiAvU', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 5: I Don’t Have To Give Up', 'Large Group Full Program'),
('YPWE3000018', 'BVLAFRqSzX0', 'YPLArkElY03', 18, 'exHb8KUGaAZ', 'BVLAFRqSzX0', 'SvoKl_NUJFo', '2WhQMhQzlYm', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 6: I Can Worship God In Truth', 'Large Group Full Program'),
('YPWE3000019', 'BVLAFRqSzX0', 'YPLArkElY03', 19, 'm6oeuy6TGEq', 'BVLAFRqSzX0', 'SvoKl_NUJFo', 'jXT3xFgGYbI', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 7: I Can Treat Others Well', 'Large Group Full Program'),
('YPWE3000020', 'BVLAFRqSzX0', 'YPLArkElY03', 20, 'WmhkvNs_Ztz', 'BVLAFRqSzX0', 'SvoKl_NUJFo', 'QYBubY6jvQN', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 8: I Can Show Love To All', 'Large Group Full Program'),
('YPWE3000021', 'BVLAFRqSzX0', 'YPLArkElY03', 21, 'L2_f9yRpojj', 'BVLAFRqSzX0', 'CjeQDiTDrGV', '1p9vpjmJUC6', 'The Bible', 'The Bible Week 1: The Bible is True', 'Large Group Full Program'),
('YPWE3000022', 'BVLAFRqSzX0', 'YPLArkElY03', 22, 'Ql7PE5AbNRY', 'BVLAFRqSzX0', 'CjeQDiTDrGV', 'RDb0hGZgABH', 'The Bible', 'The Bible Week 2: The Bible Guides Us', 'Large Group Full Program'),
('YPWE3000023', 'BVLAFRqSzX0', 'YPLArkElY03', 23, 'EF8Zaq0syOC', 'BVLAFRqSzX0', 'CjeQDiTDrGV', 'hsRFG0zEJ6F', 'The Bible', 'The Bible Week 3: The Bible Helps Us', 'Large Group Full Program'),
('YPWE3000024', 'BVLAFRqSzX0', 'YPLArkElY03', 24, 'krDmxXenx7V', 'BVLAFRqSzX0', 'CjeQDiTDrGV', '0dHZCkKLZCk', 'The Bible', 'The Bible Week 4: The Bible Trains Us', 'Large Group Full Program'),
('YPWE3000025', 'BVLAFRqSzX0', 'YPLArkElY03', 25, 'PpSH00dXEhi', 'BVLAFRqSzX0', 'mKJl07eHv8c', 'yl0Mh92a0Lo', 'Tools For School', 'Tools For School Week 1: Get Wisdom', 'Large Group Full Program'),
('YPWE3000026', 'BVLAFRqSzX0', 'YPLArkElY03', 26, 'GnMaRKErf5b', 'BVLAFRqSzX0', 'mKJl07eHv8c', 'ZnXvAFD7Ws7', 'Tools For School', 'Tools For School Week 2: Discipline Is Good!', 'Large Group Full Program'),
('YPWE3000027', 'BVLAFRqSzX0', 'YPLArkElY03', 27, 'yxHc3aVVNWR', 'BVLAFRqSzX0', 'mKJl07eHv8c', 'TH1yJp-wFp7', 'Tools For School', 'Tools For School Week 3: Listen To Wise People!', 'Large Group Full Program'),
('YPWE3000028', 'BVLAFRqSzX0', 'YPLArkElY03', 28, 'mC7D-ZjSswf', 'BVLAFRqSzX0', 'mKJl07eHv8c', 'jEUqy7YuEvK', 'Tools For School', 'Tools For School Week 4: Work Hard!', 'Large Group Full Program'),
('YPWE3000029', 'BVLAFRqSzX0', 'YPLArkElY03', 29, 'S6SJ3qKPIq5', 'BVLAFRqSzX0', 'ezhrBpNaWYM', '05eEyY6bjkN', 'Tough Questions', 'Tough Questions Week 1: God Is Good, All The Time!', 'Large Group Full Program'),
('YPWE3000030', 'BVLAFRqSzX0', 'YPLArkElY03', 30, 'eWgpqYBQCGw', 'BVLAFRqSzX0', 'ezhrBpNaWYM', 'zBKFN0kWnyw', 'Tough Questions', 'Tough Questions Week 2: God Will Always Love Me!', 'Large Group Full Program'),
('YPWE3000031', 'BVLAFRqSzX0', 'YPLArkElY03', 31, 'uIUPi5LUu8V', 'BVLAFRqSzX0', 'ezhrBpNaWYM', 'uOOSOOSX20C', 'Tough Questions', 'Tough Questions Week 3: God Makes Me Strong!', 'Large Group Full Program'),
('YPWE3000032', 'BVLAFRqSzX0', 'YPLArkElY03', 32, 'V6t3j9ADiho', 'BVLAFRqSzX0', 'ezhrBpNaWYM', '3i_YKc02VFD', 'Tough Questions', 'Tough Questions Week 4: God Can Turn Things Around!', 'Large Group Full Program'),
('YPWE3000033', 'BVLAFRqSzX0', 'YPLArkElY03', 33, 'CjQ0spl2kRy', 'BVLAFRqSzX0', 'ZRBS7YRbenP', '83xV8gDVZ0j', 'Thanks & Giving', 'Thanks & Giving Week 1: Don''t Forget To Say Thanks!', 'Large Group Full'),
('YPWE3000034', 'BVLAFRqSzX0', 'YPLArkElY03', 34, 'BwUxyTM00Br', 'BVLAFRqSzX0', 'ZRBS7YRbenP', 's5FhMn5EJlZ', 'Thanks & Giving', 'Thanks & Giving Week 2: Don''t Grumble, Say Thanks!', 'Large Group Full'),
('YPWE3000035', 'BVLAFRqSzX0', 'YPLArkElY03', 35, 'DDSnnwJmLxv', 'BVLAFRqSzX0', 'ZRBS7YRbenP', 'avSAh1JPgZO', 'Thanks & Giving', 'Thanks &  Giving Week 3: We All Have Something To Give!', 'Large Group Full'),
('YPWE3000036', 'BVLAFRqSzX0', 'YPLArkElY03', 36, 'ijqdIt1NchQ', 'BVLAFRqSzX0', 'ZRBS7YRbenP', 'iK4oKhTTLI1', 'Thanks & Giving', 'Thanks & Giving Week 4: No Gift Is Too Small!', 'Large Group Full'),
('YPWE3000037', 'BVLAFRqSzX0', 'YPLArkElY03', 37, '9a0Ra0vl0oP', 'BVLAFRqSzX0', 'w6SXZatWHqA', 'UuCed9InQwk', 'Great Joy (Christmas)', 'Great Joy Week 1: God Keeps His Promises!', 'Large Group Full'),
('YPWE3000038', 'BVLAFRqSzX0', 'YPLArkElY03', 38, 'NiJthTGJyvE', 'BVLAFRqSzX0', 'w6SXZatWHqA', '5SGQnFSRRZj', 'Great Joy (Christmas)', 'Great Joy Week 2: God Loves Us All The Same!', 'Large Group Full Program'),
('YPWE3000039', 'BVLAFRqSzX0', 'YPLArkElY03', 39, 'DkcAhg0RlD8', 'BVLAFRqSzX0', 'w6SXZatWHqA', '2TCCi0tQInr', 'Great Joy (Christmas)', 'Great Joy Week 3: Jesus Is Our Savior!', 'Large Group Full Program'),
('YPWE3000040', 'BVLAFRqSzX0', 'YPLArkElY03', 40, 'd1CnTY4b9iU', 'BVLAFRqSzX0', 'w6SXZatWHqA', '6vngcx1vr8l', 'Great Joy (Christmas)', 'Great Joy Week 4: Jesus Is King!', 'Large Group Full Program'),
('YPWES000001', 'BVLAFRqSzX0', 'YPLArkElSpc', 1, 'PB5-PfxtjOk', 'BVLAFRqSzX0', 'Tkt4LQsGdq7', 'ULsgCdAg3Uq', 'Yes To Jesus', 'Yes To Jesus Week 1: I Can Say Yes To Jesus!', 'Large Group Full Program'),
('YPWES000002', 'BVLAFRqSzX0', 'YPLArkElSpc', 2, 'yzWf4iATBcL', 'BVLAFRqSzX0', '-yE9wFBcehh', 'Tj2yUjjzUiI', 'Super Bowl Sunday', 'Super Bowl Sunday Week 1: I’m Part of God’s Team!', 'Large Group Full Program'),
('YPWES000003', 'BVLAFRqSzX0', 'YPLArkElSpc', 3, 'LsRDsSG89oo', 'BVLAFRqSzX0', 'CvBY2a-rRT6', '4bEgua63pPE', 'Back To School Bash', 'Back To School Bash : I''m Loved, So I Can Love!', 'Large Group Full Program'),
('YPWES000004', 'BVLAFRqSzX0', 'YPLArkElSpc', 4, 'sJJPjcwA-vF', 'BVLAFRqSzX0', '1RIO2PxoMst', 'YMztcKZii0N', 'Easter', 'Easter stand alone lesson: Easter Is Good News!', 'Large Group'),
('YPWJ1000001', 'BVLAFRqSzX0', 'YPLArkJrY01', 1, 'ksLtUOL1srJ', 'BVLAFRqSzX1', '-l3f-Axq9Pw', 'HM8BdnXkid1', 'The Helper', 'The Helper Week 1: The Holy Spirit Is Our Helper', 'Large Group'),
('YPWJ1000002', 'BVLAFRqSzX0', 'YPLArkJrY01', 2, 'CjD-5Fvjfeq', 'BVLAFRqSzX1', '-l3f-Axq9Pw', '700Qc90TGbp', 'The Helper', 'The Helper Week 2: The Holy Spirit Is Our Guide', 'Large Group'),
('YPWJ1000003', 'BVLAFRqSzX0', 'YPLArkJrY01', 3, '79BG3drNPkf', 'BVLAFRqSzX1', '-l3f-Axq9Pw', 'j4-2JcqJdds', 'The Helper', 'The Helper Week 3: The Holy Spirit Is Our Comforter', 'Large Group'),
('YPWJ1000004', 'BVLAFRqSzX0', 'YPLArkJrY01', 4, 'YyTOXCdXXXz', 'BVLAFRqSzX1', '-l3f-Axq9Pw', 'V4mX5zxlcdF', 'The Helper', 'The Helper Week 4: The Holy Spirit Is Our Source', 'Large Group'),
('YPWJ1000005', 'BVLAFRqSzX0', 'YPLArkJrY01', 5, '6iukCbq9CRy', 'BVLAFRqSzX1', 'WapuOHrIrMa', '5kYS0igpIxO', 'Love God, Love Others', 'Love God, Love Others Week 1: Love God The Most', 'Large Group'),
('YPWJ1000006', 'BVLAFRqSzX0', 'YPLArkJrY01', 6, 'jyofZ9wwD70', 'BVLAFRqSzX1', 'WapuOHrIrMa', 'Zv6cBlvmWI7', 'Love God, Love Others', 'Love God, Love Others Week 2: Love God With Everything', 'Large Group'),
('YPWJ1000007', 'BVLAFRqSzX0', 'YPLArkJrY01', 7, 'eda4xTos2ml', 'BVLAFRqSzX1', 'WapuOHrIrMa', 'lcODO4115Oe', 'Love God, Love Others', 'Love God, Love Others Week 3:  Love Your Neighbor', 'Large Group'),
('YPWJ1000008', 'BVLAFRqSzX0', 'YPLArkJrY01', 8, 'wRoC4hQqfJr', 'BVLAFRqSzX1', 'WapuOHrIrMa', '03mkY0SffRJ', 'Love God, Love Others', 'Love God, Love Others Week 4: Love Your Neighbor As Yourself', 'Large Group'),
('YPWJ1000009', 'BVLAFRqSzX0', 'YPLArkJrY01', 9, '8BO5CzAtjy2', 'BVLAFRqSzX1', 'y8fsHCL1njq', 'OKWlS-D42ym', 'Jesus Is', 'Jesus Is Week 1: Jesus Is The Bread Of Life', 'Large Group'),
('YPWJ1000010', 'BVLAFRqSzX0', 'YPLArkJrY01', 10, 'fe9VEO0y-SO', 'BVLAFRqSzX1', 'y8fsHCL1njq', '1Ocar-c4T5l', 'Jesus Is', 'Jesus Is Week 2: Jesus Is The Good Shepherd', 'Large Group'),
('YPWJ1000011', 'BVLAFRqSzX0', 'YPLArkJrY01', 11, '8vM7wvVL0D1', 'BVLAFRqSzX1', 'y8fsHCL1njq', '_1L9KNl4sX5', 'Jesus Is', 'Jesus Is Week 3: Jesus Is The Light Of The World', 'Large Group'),
('YPWJ1000012', 'BVLAFRqSzX0', 'YPLArkJrY01', 12, 'rfP_1ZSOaPR', 'BVLAFRqSzX1', 'y8fsHCL1njq', 'vkEvxtsI8Tp', 'Jesus Is', 'Jesus Is Week 4: Jesus Is The Resurrection And The Life', 'Large Group'),
('YPWJ1000013', 'BVLAFRqSzX0', 'YPLArkJrY01', 13, 'b9iUd3RzEaa', 'BVLAFRqSzX1', 'pmgReLUu6bT', '3-r8PPRV5ev', 'Let''s Chat', 'Let''s Chat Week 1:  I Can Pray', 'Large Group'),
('YPWJ1000014', 'BVLAFRqSzX0', 'YPLArkJrY01', 14, 'EW7V9rt9MM5', 'BVLAFRqSzX1', 'pmgReLUu6bT', 'qGbFkiEx-wb', 'Let''s Chat', 'Let''s Chat Week 2:  I Can Pray Anytime', 'Large Group'),
('YPWJ1000015', 'BVLAFRqSzX0', 'YPLArkJrY01', 15, 'GW8LxHbMoOV', 'BVLAFRqSzX1', 'pmgReLUu6bT', 'RrS1jvMD1LB', 'Let''s Chat', 'Let''s Chat Week 3: I Can Pray From My Heart', 'Large Group'),
('YPWJ1000016', 'BVLAFRqSzX0', 'YPLArkJrY01', 16, '4iF97Wv1ohT', 'BVLAFRqSzX1', 'pmgReLUu6bT', 'EpNiABVgh5M', 'Let''s Chat', 'Let''s Chat Week 4: God Listens When I Pray', 'Large Group'),
('YPWJ1000017', 'BVLAFRqSzX0', 'YPLArkJrY01', 17, '9WjR4hfumE9', 'BVLAFRqSzX1', 'Rkgp2naMJj0', 'yem20bvTxTr', 'Go (Missions Series)', 'Go Week 1: I Can Go!', 'Large Group'),
('YPWJ1000018', 'BVLAFRqSzX0', 'YPLArkJrY01', 18, '7rDCxxDfzen', 'BVLAFRqSzX1', 'Rkgp2naMJj0', 'i06lXqQxtH3', 'Go (Missions Series)', 'Go Week 2: I Can Tell!', 'Large Group'),
('YPWJ1000019', 'BVLAFRqSzX0', 'YPLArkJrY01', 19, 'MGCA1Bw9-0Y', 'BVLAFRqSzX1', 'Rkgp2naMJj0', '0t1r0UOL5ji', 'Go (Missions Series)', 'Go Week 3: I Can Give!', 'Large Group'),
('YPWJ1000020', 'BVLAFRqSzX0', 'YPLArkJrY01', 20, 'fdTtn07YvcS', 'BVLAFRqSzX1', 'Rkgp2naMJj0', 'J6PSlbxIejn', 'Go (Missions Series)', 'Go Week 4: I Can Keep Going!', 'Large Group'),
('YPWJ1000021', 'BVLAFRqSzX0', 'YPLArkJrY01', 21, 'p2IZd6uJq9Z', 'BVLAFRqSzX1', 'bKo06vepJwb', 'M0y4USQebQJ', 'Summer to the Max', 'Summer to the Max Week 1: I Can Honor God', 'Large Group'),
('YPWJ1000022', 'BVLAFRqSzX0', 'YPLArkJrY01', 22, 'ShjIyvIHwcE', 'BVLAFRqSzX1', 'bKo06vepJwb', 'ss4r-xjQMt9', 'Summer to the Max', 'Summer to the Max Week 2: I Can Obey God', 'Large Group'),
('YPWJ1000023', 'BVLAFRqSzX0', 'YPLArkJrY01', 23, 'KubmLd78pH-', 'BVLAFRqSzX1', 'bKo06vepJwb', 'YorjnYdh-DS', 'Summer to the Max', 'Summer to the Max Week 3: I Can Believe God’s Word', 'Large Group'),
('YPWJ1000024', 'BVLAFRqSzX0', 'YPLArkJrY01', 24, '0t-9iBIA3mI', 'BVLAFRqSzX1', 'bKo06vepJwb', 'AJnRBvWi6oo', 'Summer to the Max', 'Summer to the Max Week 4: I Can Do The Right Thing', 'Large Group'),
('YPWJ1000025', 'BVLAFRqSzX0', 'YPLArkJrY01', 25, 'C0Sa8vF57Kg', 'BVLAFRqSzX1', 'bKo06vepJwb', 'spDojZaYJPP', 'Summer to the Max', 'Summer to the Max Week 5: I Can Serve', 'Large Group'),
('YPWJ1000026', 'BVLAFRqSzX0', 'YPLArkJrY01', 26, 'pFLfQVV7YgY', 'BVLAFRqSzX1', 'bKo06vepJwb', 'cvp2QVlxbIl', 'Summer to the Max', 'Summer to the Max Week 6: I Can Change', 'Large Group'),
('YPWJ1000027', 'BVLAFRqSzX0', 'YPLArkJrY01', 27, 'WAa-wbG0ytY', 'BVLAFRqSzX1', 'bKo06vepJwb', 'nWhtdL137N-', 'Summer to the Max', 'Summer to the Max Week 7: I Can Speak the Truth', 'Large Group'),
('YPWJ1000028', 'BVLAFRqSzX0', 'YPLArkJrY01', 28, '216Iss0YxeY', 'BVLAFRqSzX1', 'bKo06vepJwb', 'i1tSn3Kxgzk', 'Summer to the Max', 'Summer to the Max Week 8: I Can Step Up', 'Large Group'),
('YPWJ1000029', 'BVLAFRqSzX0', 'YPLArkJrY01', 29, '9UVWieM88w0', 'BVLAFRqSzX1', 'LmI0uSaYkU6', 'OeVlvVdRG65', 'In Step', 'In Step Week 1: Put Others First', 'Large Group'),
('YPWJ1000030', 'BVLAFRqSzX0', 'YPLArkJrY01', 30, 'kVJWlFqxzTD', 'BVLAFRqSzX1', 'LmI0uSaYkU6', 'Sh-JSjHHQlI', 'In Step', 'In Step Week 2: Be Happy No Matter What', 'Large Group'),
('YPWJ1000031', 'BVLAFRqSzX0', 'YPLArkJrY01', 31, 'JPLCAtxnX8S', 'BVLAFRqSzX1', 'LmI0uSaYkU6', 'hI8a_crLu41', 'In Step', 'In Step Week 3: Have a Peaceful Heart And Mind', 'Large Group'),
('YPWJ1000032', 'BVLAFRqSzX0', 'YPLArkJrY01', 32, 'aSgqtHrA3LX', 'BVLAFRqSzX1', 'LmI0uSaYkU6', 'yPv_XDJSOVC', 'In Step', 'In Step Week 4: Be Willing To Wait', 'Large Group'),
('YPWJ1000033', 'BVLAFRqSzX0', 'YPLArkJrY01', 33, 'agxG3HmfU8A', 'BVLAFRqSzX1', 'LmI0uSaYkU6', '0023VPx_ekj', 'In Step', 'In Step Week 5: Care For Others', 'Large Group'),
('YPWJ1000034', 'BVLAFRqSzX0', 'YPLArkJrY01', 34, 'MyhVbeTWbyn', 'BVLAFRqSzX1', 'LmI0uSaYkU6', 'rBihTGrBkkc', 'In Step', 'In Step Week 6: Give Without Getting Back', 'Large Group'),
('YPWJ1000035', 'BVLAFRqSzX0', 'YPLArkJrY01', 35, 'EUAZU2n2uh6', 'BVLAFRqSzX1', 'LmI0uSaYkU6', 'mPpg6F6kX9W', 'In Step', 'In Step Week 7: Count On Me', 'Large Group'),
('YPWJ1000036', 'BVLAFRqSzX0', 'YPLArkJrY01', 36, 'NyQq-aSbRt7', 'BVLAFRqSzX1', 'LmI0uSaYkU6', 'rm4SHFknvVC', 'In Step', 'In Step Week 8: Use Your Power to Help', 'Large Group'),
('YPWJ1000037', 'BVLAFRqSzX0', 'YPLArkJrY01', 37, '0TRRqhDDWkW', 'BVLAFRqSzX1', 'LmI0uSaYkU6', 'MKuICUyrKMI', 'In Step', 'In Step Week 9: Stay In Charge', 'Large Group'),
('YPWJ1000038', 'BVLAFRqSzX0', 'YPLArkJrY01', 38, '4LqeyHLDmkW', 'BVLAFRqSzX1', 'Ck8vidI1P51', 'AMC3XEYc3W5', 'The Bible Tells Me So', 'The Bible Tells Me So Week 1: The Bible Tells Me Who God Is', 'Large Group'),
('YPWJ1000039', 'BVLAFRqSzX0', 'YPLArkJrY01', 39, 'BKcYwd2Sd89', 'BVLAFRqSzX1', 'Ck8vidI1P51', 'LDhhQALjLq-', 'The Bible Tells Me So', 'The Bible Tells Me So Week 2: The Bible Tells Me Who I Am', 'Large Group'),
('YPWJ1000040', 'BVLAFRqSzX0', 'YPLArkJrY01', 40, 'M7OYAvByIMj', 'BVLAFRqSzX1', 'Ck8vidI1P51', '9JPQwgLcBo4', 'The Bible Tells Me So', 'The Bible Tells Me So Week 3: The Bible Tells Me What God Can Do', 'Large Group'),
('YPWJ1000041', 'BVLAFRqSzX0', 'YPLArkJrY01', 41, 'Vrh9O-le9m0', 'BVLAFRqSzX1', 'Ck8vidI1P51', 'spt79SRo7Of', 'The Bible Tells Me So', 'The Bible Tells Me So Week 4: The Bible Tells Me What I Can Do', 'Large Group'),
('YPWJ1000042', 'BVLAFRqSzX0', 'YPLArkJrY01', 42, 'kq0xx0T7pNH', 'BVLAFRqSzX1', 'NNyNiWWSUJ3', 'gknyz3MVuQF', 'I’m Part of God''s Big Plan', 'I''m Part Of God''s Big Plan Week 1: Believe What God Says!', 'Large Group'),
('YPWJ1000043', 'BVLAFRqSzX0', 'YPLArkJrY01', 43, 'wzL-oUibVkF', 'BVLAFRqSzX1', 'NNyNiWWSUJ3', 'jJQ3PfAsnZN', 'I’m Part of God''s Big Plan', 'I''m Part Of God''s Big Plan Week 2: Don''t Give Up!', 'Large Group'),
('YPWJ1000044', 'BVLAFRqSzX0', 'YPLArkJrY01', 44, 'xwYzOSXIHXD', 'BVLAFRqSzX1', 'NNyNiWWSUJ3', 'sV1Au4Ywmjf', 'I’m Part of God''s Big Plan', 'I''m Part Of God''s Big Plan Week 3: Use Your Gifts!', 'Large Group'),
('YPWJ1000045', 'BVLAFRqSzX0', 'YPLArkJrY01', 45, 'mZTev1uEMVe', 'BVLAFRqSzX1', 'NNyNiWWSUJ3', 'CZhwsTVHPO8', 'I’m Part of God''s Big Plan', 'I''m Part Of God''s Big Plan Week 4: Forgive And Let Go!', 'Large Group'),
('YPWJ1000046', 'BVLAFRqSzX0', 'YPLArkJrY01', 46, 'GIjxZBH_Z0A', 'BVLAFRqSzX1', 'w1H__m3om_3', 'xZ4y1LNovj6', 'The Good News of Christmas', 'The Good News of Christmas Week 1: God Can Use Me!', 'Large Group'),
('YPWJ1000047', 'BVLAFRqSzX0', 'YPLArkJrY01', 47, 'Qho-BnFEdgw', 'BVLAFRqSzX1', 'w1H__m3om_3', '09m2K2aoLtq', 'The Good News of Christmas', 'The Good News of Christmas Week 2: God Wants Me In His Family!', 'Large Group'),
('YPWJ1000048', 'BVLAFRqSzX0', 'YPLArkJrY01', 48, '6kd3AHEKXN1', 'BVLAFRqSzX1', 'w1H__m3om_3', '8FIadtORM7v', 'The Good News of Christmas', 'The Good News of Christmas Week 3: Jesus Brings Joy At Christmas!', 'Large Group'),
('YPWJ2000001', 'BVLAFRqSzX0', 'YPLArkJrY02', 1, 'mMmhUvbjeQ4', 'BVLAFRqSzX1', 'kuulvFANatW', 'mCmXMeI5kNu', 'Psalm 23', 'Psalm 23 Week 1: The Lord Is My Shepherd', 'Large Group'),
('YPWJ2000002', 'BVLAFRqSzX0', 'YPLArkJrY02', 2, 'UpHBfjSdAO7', 'BVLAFRqSzX1', 'kuulvFANatW', 'NyiN64d1B0W', 'Psalm 23', 'Psalm 23 Week 2: The Lord Is My Protector', 'Large Group'),
('YPWJ2000003', 'BVLAFRqSzX0', 'YPLArkJrY02', 3, 'KUyGbPaeZzc', 'BVLAFRqSzX1', 'kuulvFANatW', 'jNcej_abiKy', 'Psalm 23', 'Psalm 23 Week 3: The Lord Is My Provider', 'Large Group'),
('YPWJ2000004', 'BVLAFRqSzX0', 'YPLArkJrY02', 4, '3k-Slk75nZL', 'BVLAFRqSzX1', 'kuulvFANatW', '84k0-yEqpgr', 'Psalm 23', 'Psalm 23 Week 4: The Lord Is My Hope', 'Large Group'),
('YPWJ2000005', 'BVLAFRqSzX0', 'YPLArkJrY02', 5, 'kiCDsVUjdXW', 'BVLAFRqSzX1', 'vEA2KwRpN90', 'OJXXQyGb8B9', 'Guard Your Heart', 'Guard Your Heart Week 1: Guard Your Heart!', 'Large Group'),
('YPWJ2000006', 'BVLAFRqSzX0', 'YPLArkJrY02', 6, '0Wded210osZ', 'BVLAFRqSzX1', 'vEA2KwRpN90', 'fVQheBN4f54', 'Guard Your Heart', 'Guard Your Heart Week 2: Keep Out The Bad!', 'Large Group'),
('YPWJ2000007', 'BVLAFRqSzX0', 'YPLArkJrY02', 7, 'ck-Smiso3k6', 'BVLAFRqSzX1', 'vEA2KwRpN90', 'vsuqY1JnKAo', 'Guard Your Heart', 'Guard Your Heart Week 3: Put In The Good!', 'Large Group'),
('YPWJ2000008', 'BVLAFRqSzX0', 'YPLArkJrY02', 8, 'Lcm-IkpGm0q', 'BVLAFRqSzX1', '7t3x7O9JVXh', 'YviOXfDJ36e', 'Winter to the Max', 'Winter to the Max Week 1: I Will Value Jesus!', 'Large Group'),
('YPWJ2000009', 'BVLAFRqSzX0', 'YPLArkJrY02', 9, 'sRXZ-cnepDj', 'BVLAFRqSzX1', '7t3x7O9JVXh', '2x0_pi9W-4k', 'Winter to the Max', 'Winter to the Max Week 2: I Will Follow Jesus', 'Large Group'),
('YPWJ2000010', 'BVLAFRqSzX0', 'YPLArkJrY02', 10, 'PSuDw1mY0xL', 'BVLAFRqSzX1', '7t3x7O9JVXh', 'rhIV-qmoUT1', 'Winter to the Max', 'Winter to the Max Week 3: I Will Listen To Jesus', 'Large Group'),
('YPWJ2000011', 'BVLAFRqSzX0', 'YPLArkJrY02', 11, 'cgORdLzGRpg', 'BVLAFRqSzX1', '7t3x7O9JVXh', 't_sA-bmuNar', 'Winter to the Max', 'Winter to the Max Week 4: I Will Obey Jesus', 'Large Group'),
('YPWJ2000012', 'BVLAFRqSzX0', 'YPLArkJrY02', 12, 'aN1kAQnTF0Y', 'BVLAFRqSzX1', 'jNnbAcO106E', 'DJMj2dQda0t', 'Power Up (Easter Series)', 'Power Up For Easter : I Can Obey! Easter Lesson', 'Large Group'),
('YPWJ2000013', 'BVLAFRqSzX0', 'YPLArkJrY02', 13, 'kdwJT0qFEsF', 'BVLAFRqSzX1', 'jNnbAcO106E', 'DUTb9ljx-bf', 'Power Up (Easter Series)', 'Power Up For Easter Week 2: I Can Serve!', 'Large Group'),
('YPWJ2000014', 'BVLAFRqSzX0', 'YPLArkJrY02', 14, '8CEF3yACzSL', 'BVLAFRqSzX1', 'jNnbAcO106E', 'vLKjO2LREWo', 'Power Up (Easter Series)', 'Power Up For Easter Week 3: I Can Be Humble!', 'Large Group'),
('YPWJ2000015', 'BVLAFRqSzX0', 'YPLArkJrY02', 15, 'fzgsCZYInP5', 'BVLAFRqSzX1', 'jNnbAcO106E', 'oasg7CmHQlv', 'Power Up (Easter Series)', 'Power Up For Easter Week 4: I can Make Wise Choices', 'Large Group'),
('YPWJ2000016', 'BVLAFRqSzX0', 'YPLArkJrY02', 16, 'Uc6rG-Pf4D0', 'BVLAFRqSzX1', 'SsaUGYHFMyd', '4pP8q5MCsjB', 'Touring the Psalms', 'Touring the Psalms Week 1: I Will Praise God', 'Large Group'),
('YPWJ2000017', 'BVLAFRqSzX0', 'YPLArkJrY02', 17, 'YLFWYmg30jp', 'BVLAFRqSzX1', 'SsaUGYHFMyd', 'QUbgSm9MXur', 'Touring the Psalms', 'Touring the Psalms Week 2: I Praise God Because He Keeps His Promises', 'Large Group'),
('YPWJ2000018', 'BVLAFRqSzX0', 'YPLArkJrY02', 18, 'u7SLHtUb2Lw', 'BVLAFRqSzX1', 'SsaUGYHFMyd', 'yCWnPHR3j-G', 'Touring the Psalms', 'Touring the Psalms Week 3: I Won’t Stop Praising God', 'Large Group'),
('YPWJ2000019', 'BVLAFRqSzX0', 'YPLArkJrY02', 19, 'FguTrFZpGsN', 'BVLAFRqSzX1', 'SsaUGYHFMyd', 'BXj3G-5kIaH', 'Touring the Psalms', 'Touring the Psalms Week 4:  I Will Remember To Praise God', 'Large Group'),
('YPWJ2000020', 'BVLAFRqSzX0', 'YPLArkJrY02', 20, 'oCToin-KkGo', 'BVLAFRqSzX1', 'lTUSqcuqyfL', 'v-nFTnXg8Dn', 'Summer To The Max, Volume 2', 'Summer To The Max: Kick- Off', 'Large Group'),
('YPWJ2000021', 'BVLAFRqSzX0', 'YPLArkJrY02', 21, '_7WRXuVI0rY', 'BVLAFRqSzX1', 'lTUSqcuqyfL', 'QOK48CY5lK1', 'Summer To The Max, Volume 2', 'Summer To The Max Lesson 1: I Am Helped', 'Large Group'),
('YPWJ2000022', 'BVLAFRqSzX0', 'YPLArkJrY02', 22, 'Z0S-DtGZNPQ', 'BVLAFRqSzX1', 'lTUSqcuqyfL', 'A8viZfk9Clo', 'Summer To The Max, Volume 2', 'Summer To The Max Lesson 2: I Am Comforted', 'Large Group'),
('YPWJ2000023', 'BVLAFRqSzX0', 'YPLArkJrY02', 23, 'xwVCi3WLSdd', 'BVLAFRqSzX1', 'lTUSqcuqyfL', 'rgbzHwrCjQC', 'Summer To The Max, Volume 2', 'Summer To The Max Lesson 3: I Am Humble', 'Large Group'),
('YPWJ2000024', 'BVLAFRqSzX0', 'YPLArkJrY02', 24, 'F7WydKjX_pZ', 'BVLAFRqSzX1', 'lTUSqcuqyfL', 'XARe2KbajoE', 'Summer To The Max, Volume 2', 'Summer To The Max Lesson 4: I Am Full', 'Large Group'),
('YPWJ2000025', 'BVLAFRqSzX0', 'YPLArkJrY02', 25, 'FVWVA6uY07L', 'BVLAFRqSzX1', 'lTUSqcuqyfL', 'kSKOB9UNeCi', 'Summer To The Max, Volume 2', 'Summer To The Max Lesson 5: I Am Merciful', 'Large Group'),
('YPWJ2000026', 'BVLAFRqSzX0', 'YPLArkJrY02', 26, '8WjLRh1DOwV', 'BVLAFRqSzX1', 'lTUSqcuqyfL', 'Bo2Q3SThkmC', 'Summer To The Max, Volume 2', 'Summer To The Max Lesson 6: I Am Sincere', 'Large Group'),
('YPWJ2000027', 'BVLAFRqSzX0', 'YPLArkJrY02', 27, 'lWyALYyAJti', 'BVLAFRqSzX1', 'lTUSqcuqyfL', 'waOH-kB8fk4', 'Summer To The Max, Volume 2', 'Summer To The Max Lesson 7: I Am A Peacemaker', 'Large Group'),
('YPWJ2000028', 'BVLAFRqSzX0', 'YPLArkJrY02', 28, 'FaNULEY0v8U', 'BVLAFRqSzX1', 'lTUSqcuqyfL', 'Rs9qs5lzIXx', 'Summer To The Max, Volume 2', 'Summer To The Max Lesson 8: I Am Happy No Matter What', 'Large Group'),
('YPWJ2000029', 'BVLAFRqSzX0', 'YPLArkJrY02', 29, '46Ryu3UuSI-', 'BVLAFRqSzX1', 'ImsvNBavk2L', 'hdQ2on7EkaA', 'Peace', 'Peace Week 1: I Can Have Peace When I’m Angry', 'Large Group'),
('YPWJ2000030', 'BVLAFRqSzX0', 'YPLArkJrY02', 30, 'POqYkM0Ui0f', 'BVLAFRqSzX1', 'ImsvNBavk2L', 'DlYV5QHSz0I', 'Peace', 'Peace Week 2: I Can Have Peace When I’m Afraid', 'Large Group'),
('YPWJ2000031', 'BVLAFRqSzX0', 'YPLArkJrY02', 31, '01bmryvWp1j', 'BVLAFRqSzX1', 'ImsvNBavk2L', 'Yd0Q3dtp2-8', 'Peace', 'Peace Week 3: I Can Have Peace When I’m Sad', 'Large Group'),
('YPWJ2000032', 'BVLAFRqSzX0', 'YPLArkJrY02', 32, 'HAL0Yhyf-4o', 'BVLAFRqSzX1', 'ImsvNBavk2L', 'Bhe4264ozM2', 'Peace', 'Peace Week 4: I Can Have Peace When I’m Disliked', 'Large Group'),
('YPWJ2000033', 'BVLAFRqSzX0', 'YPLArkJrY02', 33, 'XmWoi1Liblq', 'BVLAFRqSzX1', 'sTVxfglJfZl', 'S7d5mnqQ0gl', 'Upside Down', 'Upside Down Week 1: I Will Go God’s Way!', 'Large Group'),
('YPWJ2000034', 'BVLAFRqSzX0', 'YPLArkJrY02', 34, 'e5BtMyIsCXv', 'BVLAFRqSzX1', 'sTVxfglJfZl', 'XMpXuqMAg-9', 'Upside Down', 'Upside Down Week 2: I Will Only Worship God!', 'Large Group'),
('YPWJ2000035', 'BVLAFRqSzX0', 'YPLArkJrY02', 35, 'g3IVo2fZIcR', 'BVLAFRqSzX1', 'sTVxfglJfZl', 'fgFY-WYNVJw', 'Upside Down', 'Upside Down Week 3: I Won''t Celebrate Bad Things!', 'Large Group'),
('YPWJ2000036', 'BVLAFRqSzX0', 'YPLArkJrY02', 36, '5AMoJA6qd9q', 'BVLAFRqSzX1', 'sTVxfglJfZl', 'ZVoAQ-3tnJn', 'Upside Down', 'Upside Down Week 4: I Won''t Back Down', 'Large Group'),
('YPWJ2000037', 'BVLAFRqSzX0', 'YPLArkJrY02', 37, '8hp4LKqPJ-x', 'BVLAFRqSzX1', 'ozd9hrQj00y', 'ivwlSPJGHSQ', 'Don''t Fear', 'Don''t Fear Week 1: Don''t Fear, Jesus Is Strong!', 'Large Group'),
('YPWJ2000038', 'BVLAFRqSzX0', 'YPLArkJrY02', 38, 'yjhE5fW5CKz', 'BVLAFRqSzX1', 'ozd9hrQj00y', 'RvxMiSwOoS6', 'Don''t Fear', 'Don''t Fear Week 2: Don''t Fear, Jesus Wins!', 'Large Group'),
('YPWJ2000039', 'BVLAFRqSzX0', 'YPLArkJrY02', 39, 'H-60XiyhU0M', 'BVLAFRqSzX1', 'ozd9hrQj00y', '6y22g014if6', 'Don''t Fear', 'Don''t Fear Week 3: Don''t Fear, Jesus Is Just!', 'Large Group'),
('YPWJ2000040', 'BVLAFRqSzX0', 'YPLArkJrY02', 40, 'dNedLvqrjs8', 'BVLAFRqSzX1', 'ozd9hrQj00y', 'hVXGqSefk1e', 'Don''t Fear', 'Don''t Fear Week 4: Don''t Fear, Jesus Lives Forever!', 'Large Group'),
('YPWJ2000041', 'BVLAFRqSzX0', 'YPLArkJrY02', 41, 'wmtGBzWbdjP', 'BVLAFRqSzX1', 'fuTbRkYzeL4', 'hij6e2ThvxZ', 'All Aboard', 'All Aboard Week 1: I Have Faith To Give!', 'Large Group'),
('YPWJ2000042', 'BVLAFRqSzX0', 'YPLArkJrY02', 42, 'laDs5tpKj6t', 'BVLAFRqSzX1', 'fuTbRkYzeL4', 'zQ3Xhds2MSk', 'All Aboard', 'All aboard Week 2: I Have Faith To Give When Jesus Asks!', 'Large Group'),
('YPWJ2000043', 'BVLAFRqSzX0', 'YPLArkJrY02', 43, 'xxKVrgGh01K', 'BVLAFRqSzX1', 'fuTbRkYzeL4', 'kv0zhixTLt9', 'All Aboard', 'All Aboard Week 3: I Have Faith To Give Freely!', 'Large Group'),
('YPWJ2000044', 'BVLAFRqSzX0', 'YPLArkJrY02', 44, 'ro86wrOjp04', 'BVLAFRqSzX1', 'fuTbRkYzeL4', 'sLwwQAYY0TY', 'All Aboard', 'All Aboard Week 4: I Have Faith To Give What I Have!', 'Large Group'),
('YPWJ2000045', 'BVLAFRqSzX0', 'YPLArkJrY02', 45, 'mJ4tga6sc3d', 'BVLAFRqSzX1', 'IzzIETstZxV', 'VN3kV1ZKq8K', 'Better to Give (Christmas)', 'Better to Give Week 1: It''s Better To Give', 'Large Group'),
('YPWJ2000046', 'BVLAFRqSzX0', 'YPLArkJrY02', 46, '-OXBCyCzZHm', 'BVLAFRqSzX1', 'IzzIETstZxV', 'L3a2qKeBMdl', 'Better to Give (Christmas)', 'Better to Give Week 2: Make Room To Give', 'Large Group'),
('YPWJ2000047', 'BVLAFRqSzX0', 'YPLArkJrY02', 47, 'eIosxUqG0ww', 'BVLAFRqSzX1', 'IzzIETstZxV', 'pgFuIUDRlld', 'Better to Give (Christmas)', 'Better to Give Week 3: I Will Give My Best', 'Large Group'),
('YPWJ3000001', 'BVLAFRqSzX0', 'YPLArkJrY03', 1, 'PXRm1Hl3Qgn', 'BVLAFRqSzX1', 'q1VbXFBaPKr', 'eEhVIhI-W7F', 'God''s Love Is', 'God''s  Love Is Week 1: God Is Love!', 'Large Group'),
('YPWJ3000002', 'BVLAFRqSzX0', 'YPLArkJrY03', 2, 'XAGp0XXLWGT', 'BVLAFRqSzX1', 'q1VbXFBaPKr', 'twtpDW54BcB', 'God''s Love Is', 'God''s Love Is Week 2: God''s Love Is Free!', 'Large Group'),
('YPWJ3000003', 'BVLAFRqSzX0', 'YPLArkJrY03', 3, 'Tkq1ZacE3yj', 'BVLAFRqSzX1', 'q1VbXFBaPKr', 'cX9HuZQeA2g', 'God''s Love Is', 'God''s Love Is Week 3: God Loves Us No Matter What!', 'Large Group'),
('YPWJ3000004', 'BVLAFRqSzX0', 'YPLArkJrY03', 4, 'J2Fg4R1hWVY', 'BVLAFRqSzX1', 'QOzjeiZFohm', '03gUR7tjVvR', 'More Like Jesus', 'More Like Jesus Week 1: Jesus Is Holy', 'Large Group'),
('YPWJ3000005', 'BVLAFRqSzX0', 'YPLArkJrY03', 5, '03_My2SUZqy', 'BVLAFRqSzX1', 'QOzjeiZFohm', 'A9in1l5p3p8', 'More Like Jesus', 'More Like Jesus Week 2: I Love What Jesus Loves', 'Large Group'),
('YPWJ3000006', 'BVLAFRqSzX0', 'YPLArkJrY03', 6, 'cCJ07urd8Rw', 'BVLAFRqSzX1', 'QOzjeiZFohm', '7OoxnmOJ4m6', 'More Like Jesus', 'More Like Jesus Week 3: Jesus Helps Me To Be Holy', 'Large Group'),
('YPWJ3000007', 'BVLAFRqSzX0', 'YPLArkJrY03', 7, 'J0wbKtcEp26', 'BVLAFRqSzX1', 'QOzjeiZFohm', 'G4BbJqDItch', 'More Like Jesus', 'More Like Jesus Week 4: I Want To Be More Like Jesus', 'Large Group'),
('YPWJ3000008', 'BVLAFRqSzX0', 'YPLArkJrY03', 8, 'QKrhGGEiKEG', 'BVLAFRqSzX1', '9M9Wzyscx2q', 'QTmBxxCVuJ_', 'Made For Greatness', 'Made For Greatness Week 1: I Was Made Special', 'Large Group'),
('YPWJ3000009', 'BVLAFRqSzX0', 'YPLArkJrY03', 9, '33bSLMEsm7I', 'BVLAFRqSzX1', '9M9Wzyscx2q', 'IucqBnl7_a2', 'Made For Greatness', 'Made For Greatness Week 2: I Was Made Different', 'Large Group'),
('YPWJ3000010', 'BVLAFRqSzX0', 'YPLArkJrY03', 10, 'sfB9wBQ9xbl', 'BVLAFRqSzX1', '9M9Wzyscx2q', 'ndqLa9Ka8Im', 'Made For Greatness', 'Made For Greatness Week 3: I Was Made To Never Give Up', 'Large Group'),
('YPWJ3000011', 'BVLAFRqSzX0', 'YPLArkJrY03', 11, '1AcGFrs98l5', 'BVLAFRqSzX1', '9M9Wzyscx2q', '34IBQMcVGSw', 'Made For Greatness', 'Made For Greatness Week 4: I Was Made To Serve', 'Large Group'),
('YPWJ3000012', 'BVLAFRqSzX0', 'YPLArkJrY03', 12, 'znvBXzQkt8G', 'BVLAFRqSzX1', 'ezUDuR15Rj3', '30Dcy1zMDLS', 'Summer To The Max, Vol. 3', 'Summer To The Max Kickoff: I Can Grow', 'Large Group'),
('YPWJ3000013', 'BVLAFRqSzX0', 'YPLArkJrY03', 13, 'hPbfL3-Xgfk', 'BVLAFRqSzX1', 'ezUDuR15Rj3', 'qMpqTLZgEKp', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 1: I Can Trust In Jesus', 'Large Group'),
('YPWJ3000014', 'BVLAFRqSzX0', 'YPLArkJrY03', 14, 'wmMcszRG2wW', 'BVLAFRqSzX1', 'ezUDuR15Rj3', 'h9UJp3fyZdU', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 2: I Can Be More Like Jesus', 'Large Group'),
('YPWJ3000015', 'BVLAFRqSzX0', 'YPLArkJrY03', 15, 'ACQbXiU1v1b', 'BVLAFRqSzX1', 'ezUDuR15Rj3', 'mXPs8ZiDTJm', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 3: I Can Learn From Jesus', 'Large Group'),
('YPWJ3000016', 'BVLAFRqSzX0', 'YPLArkJrY03', 16, 'N-7aBGR7-QK', 'BVLAFRqSzX1', 'ezUDuR15Rj3', 'HkiH3Pb5PBb', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 4: I Can Choose My Actions', 'Large Group'),
('YPWJ3000017', 'BVLAFRqSzX0', 'YPLArkJrY03', 17, 'mJQD2mLVWkI', 'BVLAFRqSzX1', 'ezUDuR15Rj3', 'LVlLBXYly3U', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 5: I Don’t Have To Give Up', 'Large Group'),
('YPWJ3000018', 'BVLAFRqSzX0', 'YPLArkJrY03', 18, 'MMMXqhcoeay', 'BVLAFRqSzX1', 'ezUDuR15Rj3', '2q9vhYbDdOT', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 6: I Can Worship God In Truth', 'Large Group'),
('YPWJ3000019', 'BVLAFRqSzX0', 'YPLArkJrY03', 19, 'KgF_1U646xE', 'BVLAFRqSzX1', 'ezUDuR15Rj3', 'lTiB0lognBv', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 7: I Can Treat Others Well', 'Large Group'),
('YPWJ3000020', 'BVLAFRqSzX0', 'YPLArkJrY03', 20, 'AKDsnL0D0Ne', 'BVLAFRqSzX1', 'ezUDuR15Rj3', 'F6E29npYI4k', 'Summer To The Max, Vol. 3', 'Summer To The Max Lesson 8: I Can Show Love To All', 'Large Group'),
('YPWJ3000021', 'BVLAFRqSzX0', 'YPLArkJrY03', 21, '5Zf90pndrwf', 'BVLAFRqSzX1', 's0gKpF0TrlX', '5PBX5mruhyH', 'The Bible', 'The Bible Week 1: The Bible is True', 'Large Group'),
('YPWJ3000022', 'BVLAFRqSzX0', 'YPLArkJrY03', 22, 'SvYahWRpb9W', 'BVLAFRqSzX1', 's0gKpF0TrlX', '7H8crLLWOuX', 'The Bible', 'The Bible Week 2: The Bible Guides Us', 'Large Group'),
('YPWJ3000023', 'BVLAFRqSzX0', 'YPLArkJrY03', 23, '5FGQsaP7bB_', 'BVLAFRqSzX1', 's0gKpF0TrlX', 'U703NelKTJK', 'The Bible', 'The Bible Week 3: The Bible Helps Us', 'Large Group'),
('YPWJ3000024', 'BVLAFRqSzX0', 'YPLArkJrY03', 24, 'ijSmhKKZM2l', 'BVLAFRqSzX1', 's0gKpF0TrlX', 'kkdJl1y-LYD', 'The Bible', 'The Bible Week 4: The Bible Trains Us', 'Large Group'),
('YPWJ3000025', 'BVLAFRqSzX0', 'YPLArkJrY03', 25, 'TmlqU0ZXreU', 'BVLAFRqSzX1', 'jeTWaREZ2YL', 'iEGkeU81A0g', 'Tools For School', 'Tools For School Week 1: Get Wisdom', 'Large Group'),
('YPWJ3000026', 'BVLAFRqSzX0', 'YPLArkJrY03', 26, 'kZALIqGkMq1', 'BVLAFRqSzX1', 'jeTWaREZ2YL', 'bWn6Ef5r9nS', 'Tools For School', 'Tools For School Week 2: Discipline Is Good!', 'Large Group'),
('YPWJ3000027', 'BVLAFRqSzX0', 'YPLArkJrY03', 27, '0Q7PUoiKzBZ', 'BVLAFRqSzX1', 'jeTWaREZ2YL', '-QIUbcVehdJ', 'Tools For School', 'Tools For School Week 3: Listen To Wise People!', 'Large Group'),
('YPWJ3000028', 'BVLAFRqSzX0', 'YPLArkJrY03', 28, 'nkrQ1sjahme', 'BVLAFRqSzX1', 'jeTWaREZ2YL', 'AkVva8YOtTe', 'Tools For School', 'Tools For School Week 4: Work Hard!', 'Large Group'),
('YPWJ3000029', 'BVLAFRqSzX0', 'YPLArkJrY03', 29, 'ZnfQZ2ovv5c', 'BVLAFRqSzX1', '-rStA2eNSqg', '0Hjtwcr91i0', 'Tough Questions', 'Tough Questions Week 1: God Is Good, All The Time!', 'Large Group'),
('YPWJ3000030', 'BVLAFRqSzX0', 'YPLArkJrY03', 30, 'u7V4efaqZSt', 'BVLAFRqSzX1', '-rStA2eNSqg', '8Fuhhqr73-7', 'Tough Questions', 'Tough Questions Week 2: God Will Always Love Me!', 'Large Group'),
('YPWJ3000031', 'BVLAFRqSzX0', 'YPLArkJrY03', 31, 'YfAe60-vMZC', 'BVLAFRqSzX1', '-rStA2eNSqg', 'Al-G4N9pbh0', 'Tough Questions', 'Tough Questions Week 3: God Makes Me Strong!', 'Large Group'),
('YPWJ3000032', 'BVLAFRqSzX0', 'YPLArkJrY03', 32, 'hv7PxopWb93', 'BVLAFRqSzX1', '-rStA2eNSqg', '1vv8SVXgzd7', 'Tough Questions', 'Tough Questions Week 4: God Can Turn Things Around!', 'Large Group'),
('YPWJ3000033', 'BVLAFRqSzX0', 'YPLArkJrY03', 33, '76Iff0ZGy5r', 'BVLAFRqSzX1', 'lXhp0Im0faE', '0VTI40gE94i', 'Thanks & Giving', 'Thanks & Giving Week 1: Don''t Forget To Say Thanks!', 'Large Group'),
('YPWJ3000034', 'BVLAFRqSzX0', 'YPLArkJrY03', 34, 'VSAGUwUeEWq', 'BVLAFRqSzX1', 'lXhp0Im0faE', 'FP1J0N29vYu', 'Thanks & Giving', 'Thanks & Giving Week 2: Don''t Grumble, Say Thanks', 'Large Group'),
('YPWJ3000035', 'BVLAFRqSzX0', 'YPLArkJrY03', 35, 'CkC6-MS5J-m', 'BVLAFRqSzX1', 'lXhp0Im0faE', 'U29uTafCPTk', 'Thanks & Giving', 'Thanks & Giving Week 3: We All Have Something To Give!', 'Large Group'),
('YPWJ3000036', 'BVLAFRqSzX0', 'YPLArkJrY03', 36, 'DKRhhEBEQBA', 'BVLAFRqSzX1', 'lXhp0Im0faE', 'pDvC0Rcc0hI', 'Thanks & Giving', 'Thanks & Giving Week 4: No Gift Is Too Small!', 'Large Group'),
('YPWJ3000037', 'BVLAFRqSzX0', 'YPLArkJrY03', 37, 'dWECuxmPpxD', 'BVLAFRqSzX1', '6EtBqc6qmYN', '8OgzTYXu1Wd', 'Great Joy (Christmas)', 'Great Joy Week 1: God Keeps His Promises!', 'Large Group'),
('YPWJ3000038', 'BVLAFRqSzX0', 'YPLArkJrY03', 38, 'knDgIncATab', 'BVLAFRqSzX1', '6EtBqc6qmYN', 'hWG853LolgF', 'Great Joy (Christmas)', 'Great Joy Week 2: God Loves Us All The Same!', 'Large Group'),
('YPWJ3000039', 'BVLAFRqSzX0', 'YPLArkJrY03', 39, 'vhUkBuG8f9Z', 'BVLAFRqSzX1', '6EtBqc6qmYN', 'yk8Q8HlvFxq', 'Great Joy (Christmas)', 'Great Joy Week 3: Jesus Is Our Savior!', 'Large Group'),
('YPWJ3000040', 'BVLAFRqSzX0', 'YPLArkJrY03', 40, 'nqfk9zCH4Pz', 'BVLAFRqSzX1', '6EtBqc6qmYN', 'Q-uJc6bCa0R', 'Great Joy (Christmas)', 'Great Joy Week 4: Jesus Is King!', 'Large Group'),
('YPWJS000001', 'BVLAFRqSzX0', 'YPLArkJrSpc', 1, 'nwrrXuu5pKa', 'BVLAFRqSzX1', 'zRQZAMXbRRA', 'WZUB0VkpsSn', 'Yes To Jesus', 'Yes To Jesus Week 1: I Can Say Yes To Jesus!', 'Large Group'),
('YPWJS000002', 'BVLAFRqSzX0', 'YPLArkJrSpc', 2, 'IEI6DvSl8kV', 'BVLAFRqSzX1', 'r0KnXuuom5A', 'pQ-DeQleLJd', 'Super Bowl Sunday', 'Super Bowl Sunday Week 1: I’m Part of God’s Team!', 'Classroom'),
('YPWJS000003', 'BVLAFRqSzX0', 'YPLArkJrSpc', 3, 'ihecNHvU7VW', 'BVLAFRqSzX1', 'Nl1ZTpDZVrP', 'wCF9JEuEnC6', 'Back To School Bash', 'Back To School Bash : I''m Loved, So I Can Love!', 'Large Group'),
('YPWJS000004', 'BVLAFRqSzX0', 'YPLArkJrSpc', 4, 'BzjnO7iT2V-', 'BVLAFRqSzX1', 'Cye5j9LOs-u', 'HBu8zc5w8nO', 'Easter', 'Easter stand alone lesson: Easter Is Good News!', 'Large Group');

COMMIT;

-- Ark Kids Elementary Year 1: 48 weeks
-- Ark Kids Elementary Year 2: 47 weeks
-- Ark Kids Elementary Year 3: 40 weeks
-- Ark Kids Elementary Specials: 4 weeks
-- Ark Kids Junior Year 1: 48 weeks
-- Ark Kids Junior Year 2: 47 weeks
-- Ark Kids Junior Year 3: 40 weeks
-- Ark Kids Junior Specials: 4 weeks
